import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import Navbar from "@/components/static/Navbar";
import { TaskProvider } from "@/context/TaskContext";

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${dmSans.variable} `}>
      <body>
        <SidebarProvider>
          <AppSidebar />
          <main className="w-full">
            <Navbar />
            <TaskProvider>{children}</TaskProvider>
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
